name: Publish to pub.dev

on:
  push:
    tags:
    - 'dart_flutter_version-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.actor }}!"
    # permissions:
    #   id-token: write # Required for authentication using OIDC
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1